Change how language is added to select list. Instead of using 'contai…
watson-developer-cloud/language-translator-nodejs pull request #42
Opened 2017-07-24 18:58 UTC by lbandera-ibm-research

Instead of using 'contains' to check if a list item already exists in the selection list, use a filter to look for exact match so partial matches aren't considered to be already in the list. E.g. Arabic wasn't added to select list since Egyptian Arabic exists in list and the contains selector was a match.

2017-07-24 21:39 UTC, germanattanasio approved these changes

2017-07-24 21:39 UTC, germanattanasio commented on public/demo.js
> +    for (y in modelList) {
the `var` is important as it will declare the variable in the loop scope

2017-07-24 21:39 UTC, germanattanasio commented on public/demo.js
> +        var search = ($('#ulTargetLang li a').filter(function() {
use `find` instead of `filter`

2017-07-24 21:39 UTC, germanattanasio commented on public/demo.js
> +        modelListDomain = modelList[y].domain.toString();
declare the variable with `var`

2017-07-24 21:40 UTC, germanattanasio requested changes
please update the code

2017-07-25 20:08 UTC, nfriedly commented on public/demo.js
> +    for (y in modelList) {
This was actually a fix for a bug I introduced the other day - I double-defined `y` (and it failed the linter - see #41). The linter would have failed this PR if `y` wasn't declared at all. 

However, the better fix was to rename `y` to a new var name, not re-use the `y` from above. (I would have merged the fix right away, but I was asked to wait.) 

Now that #41 is merged, this change is no longer needed

2017-07-25 20:11 UTC, nfriedly commented
I fixed the merge conflict which resolved the `var` confusion.

2017-07-26 13:11 UTC, lbandera-ibm-research commented
@germanattanasio @nfriedly - Please review lines 258 -274 in function fillInDropdown. I removed the filter and used find as suggested in the previous review. If you approve, I will make the corresponding change in function updateOutputDropdownMenu.

2017-07-27 17:16 UTC, lbandera-ibm-research commented
@nfriedly @germanattanasio - Changes are complete. If you find don't require additional changes, please approve.

2017-07-27 18:25 UTC, nfriedly approved these changes

2017-07-27 18:25 UTC, merged

2017-07-27 18:26 UTC, nfriedly commented
This looks good, sorry for the delays.